services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents host node_modules from overriding container's
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DB_PATH=/app/data/mikie_sportswear.db
    volumes:
      - ./backend:/app
      - maven-repo:/root/.m2 # Caches maven dependencies
      - ./backend/data:/app/data # Persistent storage for SQLite database
    ports:
      - "8080:8080"

volumes:
  maven-repo:
